#pragma once

enum ControlPrameter {
	INITIAL_CAMERA, START_SIMULATION, ONE_FRAME, RESET_SIMULATION, STOP_AFTER_RELEASE_MOUSE, INITIAL_SIMULATION, SET_CURSOR_FORCE, OUTPUT_IMAGE, SAVE_OBJ, START_TEST, INITIAL_TEST
};

enum ObjectType {
	COLLIDER_, TETROHEDRON_, CLOTH_
};

enum PDFuncSendToThread {
    LOCAL_PROJECTION, SOLVE_SYSYTEM, MATRIX_DECOMPOSITION, UPDATE_UV, UPDATE_MATRIX, PREPARE_WOODBURY, SET_K_COLUMN, FACTORIZE_WOODBURY_K,
    UPDATE_COLLISION_STIFFNESS, VIRTUAL_LOCAL_PROJECTION, SOLVE_VIRTUAL_SYSYTEM, UPDATE_VIRTUAL_UV, UPDATE_U_FROM_VIRTUAL, GET_FRICTION
};
enum SpatialHashingFuncSendToThread {
    FIND_AROUND_PRIMITIVE, CCD_UPDATE_TARGET_POSITION,
    CCD_REFIND_TARGET_POSITION,
    SPATIAL_HASHING, FIRST_SET_COLLISION_FREE,
    VERTEX_COLLISION_INDICATOR,
    SUM_TARGET_POSITION, RESUM_TARGET_POSITION, CHECK_IF_SIDE_CHANGED, DECIDE_IF_NEED_ITERATION, CCD_CHECK_COLLISION
};
enum MeshStructFuncSendToThread {
    FACE_NORMAL, VERTEX_NORMAL, FACE_NORMAL_RENDER, VERTEX_NORMAL_RENDER
};
enum MeshStructType {
    TRIANGLE, TETROHEDRON
};

enum Iteration {
    LOCAL_GLOBAL, OUTER
};

enum StiffnessType {
    BODY_POINT_TRIANGLE, SELF_POINT_TRIANGLE, SELF_EDGE_EDGE, SELF_POINT_POINT, LENGTH, BENDING
};

enum SetStiffness {
    START_SETTING, STIFFNESS_CONFIRMED, EDIT, EDIT_LENGTH, EDIT_BENDING, EDIT_COLLISION, EDIT_BODY_POINT_TRIANGLE, EDIT_SELF_POINT_TRIANGLE, EDIT_SELF_EDGE_EDGE, EDIT_SELF_POINT_POINT
};

enum ObjectFunc {
    TRIANGLE_AABB, EDGE_AABB, VERTEX_AABB
};

enum BVHFunc {
    CAL_CENTER, CAL_MORTON
};
