#pragma once

enum ControlPrameter {
	INITIAL_CAMERA, START_SIMULATION, ONE_FRAME, RESET_SIMULATION, STOP_AFTER_RELEASE_MOUSE, INITIAL_SIMULATION, SET_CURSOR_FORCE, OUTPUT_IMAGE, SAVE_OBJ, START_TEST, INITIAL_TEST
};

enum ObjectType {
	COLLIDER, OBJECT
};

enum PDFuncSendToThread {
    LOCAL_PROJECTION, SOLVE_SYSYTEM, MATRIX_DECOMPOSITION, UPDATE_UV, SET_DIAGONAL, PREPARE_WOODBURY, SET_K_COLUMN, FACTORIZE_WOODBURY_K,
    UPDATE_COLLISION_STIFFNESS, VIRTUAL_LOCAL_PROJECTION, SOLVE_VIRTUAL_SYSYTEM, UPDATE_VIRTUAL_UV, UPDATE_U_FROM_VIRTUAL, GET_FRICTION
};
enum SpatialHashingFuncSendToThread {
    FIND_AROUND_PRIMITIVE, CCD_UPDATE_TARGET_POSITION,
    CCD_REFIND_TARGET_POSITION,
    SPATIAL_HASHING, FIRST_SET_COLLISION_FREE,
    POINT_AABB, EDGE_AABB, TRIANGLE_AABB, VERTEX_COLLISION_INDICATOR,
    SUM_TARGET_POSITION, RESUM_TARGET_POSITION, CHECK_IF_SIDE_CHANGED, DECIDE_IF_NEED_ITERATION, CCD_CHECK_COLLISION
};
enum MeshStructFuncSendToThread {
    FACE_NORMAL, VERTEX_NORMAL, FACE_NORMAL_RENDER, VERTEX_NORMAL_RENDER
};
enum MeshStructType {
    TRIANGLE, TETROHEDRON
};