#pragma once

enum ControlPrameter {
	INITIAL_CAMERA, START_SIMULATION, ONE_FRAME, RESET_SIMULATION, STOP_AFTER_RELEASE_MOUSE, INITIAL_SIMULATION, SET_CURSOR_FORCE, OUTPUT_IMAGE, SAVE_OBJ, START_TEST, INITIAL_TEST
};

enum ObjectType {
	COLLIDER_, TETROHEDRON_, CLOTH_
};

enum PDFuncSendToThread {
    LOCAL_PROJECTION, SOLVE_SYSYTEM, MATRIX_DECOMPOSITION, UPDATE_UV, UPDATE_MATRIX, //LOCAL_EDGE_LENGTH_PROJECTION,
    COLLISION_FREE_POSITION, SOLVE_SYSYTEM_WITHOUT_COLLISION, LOCAL_PROJECTION_WITHOUT_ENERGY,
    TEST_LOCAL_PROJECTION,
    PREPARE_WOODBURY, SET_K_COLUMN, FACTORIZE_WOODBURY_K,
    UPDATE_COLLISION_STIFFNESS, VIRTUAL_LOCAL_PROJECTION, SOLVE_VIRTUAL_SYSYTEM, UPDATE_VIRTUAL_UV, UPDATE_U_FROM_VIRTUAL, GET_FRICTION
};
enum SpatialHashingFuncSendToThread {
    TRIANGLE_HASHING, SCENE_AABB, SET_HASH_TOGETHER
};

enum CollisionFuncSendToThread {
    FIND_TRIANGLE_PAIRS, FIND_PRIMITIVE_AROUND, 
    GLOBAL_COLLISION_TIME, COLLISION_CONSTRAINT,
    GLOBAL_COLLISION_DETECTION, SUM_TARGET_POSITION, RE_DETECTION, RESUM_TARGET_POSITION
};

enum MeshStructFuncSendToThread {
    FACE_NORMAL, VERTEX_NORMAL, FACE_NORMAL_RENDER, VERTEX_NORMAL_RENDER, SET_VOLUME
};
enum MeshStructType {
    TRIANGLE, TETROHEDRON
};

enum Iteration {
    LOCAL_GLOBAL, OUTER
};

enum StiffnessType {
    BODY_POINT_TRIANGLE, SELF_POINT_TRIANGLE, SELF_EDGE_EDGE, SELF_POINT_POINT, LENGTH, BENDING
};

enum SetStiffness {
    START_SETTING, STIFFNESS_CONFIRMED, EDIT, EDIT_LENGTH, EDIT_BENDING, EDIT_COLLISION, EDIT_BODY_POINT_TRIANGLE, EDIT_SELF_POINT_TRIANGLE, EDIT_SELF_EDGE_EDGE, EDIT_SELF_POINT_POINT
};

enum ObjectFunc {
    VERTEX_AABB, EDGE_TRIANGLE_AABB //TRIANGLE_AABB, EDGE_AABB,
};

enum BVHFunc {
    CAL_CENTER, CAL_MORTON
};

enum RadixSortFunc {
    SET_COUNT_BUCKET, REORDER, MORTON_REORDER, SET_COUNT_BUCKET_MORTON
};